import type { Metadata } from "next";
import { Montserrat, Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./_components/Navbar";
import Footer from "./_components/Footer";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const montserrat = Montserrat({
  display: "swap",
  style: "normal",
  subsets: ["latin"],
  weight: ["500", "600", "700"],
  variable: "--font-montserrat"
})

const inter = Inter({
  display: "swap",
  style: "normal",
  subsets: ["latin"],
  weight: ["200","300", "500", "600",],
  variable: "--font-inter"
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${montserrat.variable}  mx-auto antialiased font-inter bg-black`}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
